# Generated by Django 5.0.1 on 2024-03-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
