# Generated by Django 5.0.1 on 2024-03-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=30)),
                ('location', models.EmailField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('services', models.CharField(max_length=20)),
            ],
        ),
    ]
