# Generated by Django 5.0.1 on 2024-03-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enq_name', models.CharField(max_length=30)),
                ('enq_email', models.EmailField(max_length=20)),
                ('enq_phone', models.CharField(max_length=20)),
                ('enq_location', models.CharField(max_length=20)),
                ('enq_service', models.CharField(max_length=20)),
            ],
        ),
    ]
